package forms.constants;

/* AUTO-GENERATED FILE.  DO NOT MODIFY. 
*
* This class was automatically generated by the
* entirej plugin from the form.  It
* should not be modified by hand.
 */
public class F_COMPANY {
	public static final String ID = "Company";

	public static class B_COMPANY_DETAILS {
		public static final String ID = "Company Details";
		public static final String I_DISTRICT = "district";
		public static final String I_AUTHORISEDCAPITAL = "authorisedcapital";
		public static final String I_CIN = "cin";
		public static final String I_CONTACTEMAIL = "contactemail";
		public static final String I_CITY = "city";
		public static final String I_COMPANYNAME = "companyname";
		public static final String I_COUNTRY = "country";
		public static final String I_INDUSTRY = "industry";

	}

	public static final String C_COMPANY_CANVAS = "Company Canvas";

}