package forms.constants;

/* AUTO-GENERATED FILE.  DO NOT MODIFY. 
*
* This class was automatically generated by the
* entirej plugin from the form.  It
* should not be modified by hand.
 */
public class F_MASTER_DETAIL {
	public static final String ID = "MasterDetail";

	public static class B_MASTER {
		public static final String ID = "Master";
		public static final String I_NAME = "name";
		public static final String I_ID = "id";

	}

	public static class B_DETAIL {
		public static final String ID = "Detail";
		public static final String I_ID = "id";
		public static final String I_MASTER_ID = "masterId";
		public static final String I_ADDRESS = "address";

	}

	public static class B_ADDTOOLBAR {
		public static final String ID = "addtoolbar";
		public static final String I_NEW = "new";
		public static final String I_EDIT = "edit";
		public static final String I_DELETE = "delete";

	}

	public static final String C_MASTER = "master";
	public static final String C_DETAILS_TAB = "details tab";

	public static class C_DETAILS_TAB_PAGES {
		public static final String ADDRESS = "Address";

	}

	public static final String C_ADDTOOLBAR = "addtoolbar";
	public static final String C_ADDRESS = "address";

	public static final String AC_TOOLBAR_DELETE = "TOOLBAR_DELETE";
	public static final String AC_TOOLBAR_EDIT = "TOOLBAR_EDIT";
	public static final String AC_TOOLBAR_NEW = "TOOLBAR_NEW";

}